### ISSUE TITLE
Общие моменты

### ISSUE THREAD

**Issue by DeddXey** [mapeu/Radar_emulator#3]
1. Названия модулей должны отражать содержимое. `classes` - плохое название. `point` или `detection` - уже лучше.
2. Советую почитать вот это  https://habr.com/ru/articles/767424/ В таком процессе во время merge requect/pull request очень удобно делать код ревью.
3. Давай прикрутим к  проекту mypy и pylint, почитай про них

**Comment by mapeu** [comment]
![image](https://github.com/user-attachments/assets/bb79d184-7195-4de1-8c03-70d1d8653e18)

Всё подкрутил
